### ISSUE TITLE
用户中心侧边栏导航菜单未对齐

### ISSUE THREAD

**Issue by Verrickt** [ZJU-CC98/Forum#69]
如何重现：
1. 使用浏览器打开 https://www.cc98.org/usercenter
2. 手动缩放至300%
3. F12打开控制台，在`*`下添加css规则，以显示布局边界
``` css 
* {
border: solid 1px;
}
```
可见文字部分并未完全对齐
<img width="356" alt="Screenshot 2021-10-16 132446" src="https://user-images.githubusercontent.com/11483783/137575138-847698ff-8cb9-454e-8d00-089657ac215f.png">

原因：
`.center-nav-item`的css为
``` css
.center-nav-item {
  margin-left: 1rem;
}
```
而用作导航图标的`Font-Awesome`自身宽度不同，从而导致文字无法对齐（其实图标也没有对齐，但并不容易看出来）
![image](https://user-images.githubusercontent.com/11483783/137575301-9c266b6f-4b00-4764-ad3c-85b64cc9e813.png)
更多详情请参考 https://www.cc98.org/topic/5012755
